### ISSUE TITLE
Add drawing "Part Already Exist" (4.1.1)

### ISSUE THREAD

**Issue by ZTHawk** [JanKallman/EPPlus#100]
I have a template that already has an image in one of its sheets.
Now when I add a new drawing to another sheet I get a crash.

I have attached a tempalte file (epplus_drawing_id_issue.xlsx) and here is a test code:
```
public static void Test( )
{
    Stream templateFile = new FileStream(Environment.GetEnvironmentVariable("USERPROFILE") + "/documents/epplus_drawing_id_issue.xlsx", FileMode.Open, FileAccess.Read, FileShare.Read);
    FileStream outputFile = new FileStream(Environment.GetEnvironmentVariable("USERPROFILE") + "/documents/epplus_drawing_id_issue_new.xlsx", FileMode.Create, FileAccess.ReadWrite, FileShare.None);
    using ( ExcelPackage package = new ExcelPackage(templateFile) )
    {
        ExcelWorkbook wb = package.Workbook;
        ExcelWorksheet sh = wb.Worksheets[1];
        System.Drawing.Image img_ = System.Drawing.Image.FromFile(@"c:\Users\Public\Pictures\Sample Pictures\Desert.jpg");
        ExcelPicture pic = sh.Drawings.AddPicture("logo", img_);
        pic.SetPosition(1, 1);

        package.SaveAs(outputFile);
    }
}
```

[epplus_drawing_id_issue.xlsx](https://github.com/JanKallman/EPPlus/files/1631667/epplus_drawing_id_issue.xlsx)

The crash appears within "public ExcelPicture AddPicture" (ExcelDrawing.cs). More precisely in "private XmlElement CreateDrawingXml()" (ExcelDrawings.cs)
The issue is this line:
```
_uriDrawing = new Uri(string.Format("/xl/drawings/drawing{0}.xml", Worksheet.SheetID),UriKind.Relative);
```

Excel is not generating drawings by sheet ID but in a consecutive order. The template has sheets with IDs 1, 2 and 3. Sheet with ID 2 has a drawing. That drawing has an ID equal to 1. Template generated with MS Excel 2010.

**Comment by JanKallman** [comment]
Fixed in 4.5.1
