### ISSUE TITLE
Use of Color struct from System.Windows.Media namespace (PresentationCore.dll)

### ISSUE THREAD

**Issue by DTomberge** [JanKallman/EPPlus#104]
In the ExcelColor class there is only one way to set the color via the SetColor() method. This method only excepts the color struct from the System.Drawing namespace. 
Since we use the System.Windows.Media namespace (server side) this method can not be used.
Is it possible to add an overload of SetColor() to accept the rgb-colors (byte r, byte g, byte b) or an other way so the other Color struct can be used?

**Comment by JanKallman** [comment]
Added new SetColor(alpha,red,green,blue) in 4.5.1.
