### ISSUE TITLE
.NET Core version System.IndexOutOfRangeException: Worksheet position out of range.

### ISSUE THREAD

**Issue by LeslieMurphy** [JanKallman/EPPlus#109]
Using EPPlus 4.5.0.1-beta and .NET  Framework 4.6.1 an index of one gets the first worksheet:

`Package.Workbook.Worksheets[1];`

Using EPPlus 4.5.0.1-beta and ,Net Core 2.0 we need to index by zero

`Package.Workbook.Worksheets[0];`

Zero based seems more appropriate  - but that is not the way the package behaves in the main framework.  Please document / make them consistent one way or the other.

**Comment by JanKallman** [comment]
Yes, badly documented in beta. See readme file  and sample project 4.5.1

**Comment by SheepRock** [comment]
This will be fixed for the indexes to match from both frameworks, or it will be kept this way and documented?

**Comment by LeslieMurphy** [comment]
This issue is nicely documented in the NuGet readme :-)

Kudos to Jan!

EPPlus 4.5.3.1

New features in version 4.5:
* .NET Core support
* Sparklines
* Sort method added to ExcelRange
* Bug fixes and minor changes, see below and visit
https://github.com/JanKallman/EPPlus for tutorials, samples and the latest
information

Important Notes:
Breaking change in .NET Core: The Worksheets collection will be zero based
as default.
This can be altered by setting the
ExcelPackage.Compatibility.IsWorksheets1Based to true.
.NET Core will have this property set to false, and .Net 3.5 and .Net 4
version will have this property set to true for backward compatibility
reasons.
This property can also be set via the appsettings.json file in .Net Core or
the app.config file. See sample project for examples!

**Comment by SheepRock** [comment]
Oh! Ok, I was expecting this kind of information to also be present in the EPPlus wiki.
