### ISSUE TITLE
Nuget package adds undeletable readme.txt file

### ISSUE THREAD

**Issue by ripvannwinkler** [JanKallman/EPPlus#110]
This is for 4.5.0.1-beta.  See screenshot below.

![2018-01-31 10_46_56-microsoft visual studio](https://user-images.githubusercontent.com/130069/35635536-2b4ae22a-0674-11e8-807d-7424929bd6b8.png)

This appears to happen because of the wy the nuget package is configured. The offending entry in the referenced nuget.g.props file is:

![image](https://user-images.githubusercontent.com/130069/35635577-469f966a-0674-11e8-9fe3-2743a34c72d7.png)

**Comment by JanKallman** [comment]
Fixed in version 4.5.1
