### ISSUE TITLE
Asp.Net Core MVC Example?

### ISSUE THREAD

**Issue by barbedCoil** [JanKallman/EPPlus#116]
I looked in all of the source for an example using Asp.Net Core (MVC) but only found standard Asp.Net examples.

Is there a way to get an example?
If not I'll post an example if I can get my project working.

Thanks

**Comment by VahidN** [comment]
Try this pull request https://github.com/JanKallman/EPPlus/pull/118

**Comment by barbedCoil** [comment]
Thank you, very helpful!
