### ISSUE TITLE
FYI, I got a compile time error in ExcelSparklineColor and fixed it as noted here.

### ISSUE THREAD

**Issue by mkamoski** [JanKallman/EPPlus#139]
Note: Please don't file an issue to ask a support related question. We are a small team and can't handle all questions. Questions are referred to https://stackoverflow.com/questions/tagged/epplus
If you have a bug, request of a new feature, make sure you follow these guidelines
[] Write a detailed description of your issue.

Downloaded Master. 
Unzipped and tried to compile in Visual Studio 2015.
Got compile time errors.
Fixed errors.
Compiled fine.
Sending notes to you below as FYI.

[] Attach a test to reproduce your issue, if it is a bug or unexpected behaviour. This is very important. 

n/a

[] If your issue requires a template xlsx file to be reproduced, make sure that you attach it to the issue.

n/a

Here is what I found...

            //In this file...

            //C:\Users\MyUserName\Downloads\EPPlus-master\EPPlus-master\EPPlus\Sparkline\ExcelSparklineColor.cs

            //...this line...

            //get => GetXmlNodeString("@rgb");

            //...causes a compile time error about missing brackets in Visual Studio 2015 and rewriting as follows seems to work... fixed as shown below...

...also...

            //In this file...

            //C:\Users\MyUserName\Downloads\EPPlus-master\EPPlus-master\EPPlus\Sparkline\ExcelSparklineColor.cs

            //...this line...

            //get=> GetXmlNodeDecimal("@tint");

            //...causes a compile time error about missing brackets in Visual Studio 2015 and rewriting as follows seems to work...

`        

        public string Rgb
        {
            get
            {
                return GetXmlNodeString("@rgb");
            }
            internal set
            {
                SetXmlNodeString("@rgb", value);
            }
        }

        public string Theme => GetXmlNodeString("@theme");

        public decimal Tint
        {
            get
            {
                return GetXmlNodeDecimal("@tint");
            }

            set
            {
                if (value > 1 || value < -1)
                {
                    throw (new ArgumentOutOfRangeException("Value must be between -1 and 1"));
                }
                SetXmlNodeString("@tint", value.ToString(CultureInfo.InvariantCulture));
            }
        }

`

HTH.

Thanks.

-- Mark Kamoski

**Comment by sraedler** [comment]
same to me.

**Comment by JanKallman** [comment]
This is a  feature in the new version of C#, so it should compile if you upgrade.

**Comment by mkamoski** [comment]
Why introduce a regression break for syntatic sugar? Seems like an unwarranted thing to do in this case, when old school syntax was fine in this case. Just IMHO.
