### ISSUE TITLE
EPPlus OOXML, when generating excel file then status bar dose not showing AVG and SUM for the selected range of values.

### ISSUE THREAD

**Issue by mishra14** [JanKallman/EPPlus#140]
_From @chiragcSharp on February 22, 2018 10:20_

Hi,

I'm using EPPlus to generate the excel file for various reports, I have numeric values in one column, if I select the range of that column the bottom status bar not showing the Average and SUM of the selected values. It only shows the count of the selected range. Please find the attached Image for more details.
![issue](https://user-images.githubusercontent.com/36402952/36532906-0439646a-17e8-11e8-8789-7e6c3d5a7907.png)

_Copied from original issue: NuGet/Home#6599_

**Comment by Dev-Mech** [comment]
Check what your worksheet column is setting the data type to.  I am almost positive you'll find the column type is text, usually numbers value appear on the right side of the excel cell. The attached snip is from a spreadsheet that was created entirely with EPPlus, WPF, C#.

![capture1](https://user-images.githubusercontent.com/12663418/36574739-b9e19192-180c-11e8-96e5-3eaa9b9fa5fd.JPG)

**Comment by chiragcSharp** [comment]
Hi Dev,

Thank you very much for your response. I figured out the issue. Actually the datatable from which I bound the excel has text column that is why it is treating it as text in excel too. Changing the datatype to integer worked for me.
