### ISSUE TITLE
Exception opening encrypted .XLSX whose password has been changed in Excel

### ISSUE THREAD

**Issue by SpooRancher** [JanKallman/EPPlus#146]
I have come across an issue handling password-protected spreadsheets, which occurs with versions 4.0.4 and 4.1.1. I'm doing this on Windows 7 with Excel 2010.

The steps to replicate are this:

- Create a spreadsheet using EPPlus and assign a password to encrypt it as it is saved. Encryption is set to Agile using AES256.
- Open the spreadsheet in Excel 2010 and click "Save As" In the "General Options" dialog, set a new password for opening, and save to a new file

Excel 2010 can open the new file correctly with the new password.

When opening with EPPlus, however, I get an exception using the base Exception class thrown, with the text "Dataintegrity key missmatch" (that's the exact incorrect spelling).

That scenario is fully repeatable.

If I take the original file, save it to a new file with no password; open this and save again with the new password, I get a spreadsheet that opens correctly in EEPlus.

It looks as if Excel 201 does something when a password is changed that EPPlus does not expect?

**Comment by JanKallman** [comment]
My guess is that Excel 2010 doesn't write the hmac hash. EPPlus has a check for it in the agile encryption. Can you provide a failing sample file from Excel 2010?

**Comment by SpooRancher** [comment]
Here's a test where I created an encrypted XLSX with EPPlus; changed the
password in Excel 2010; and failed to re-open in EPPlus. Excel 2010 can
re-open it correctly.

Password is "abc123" here

The code that sets the encryption when I first create the file is this:

public void SetPassword(string password)
{
    m_Excel.Encryption.Password = password;
    m_Excel.Encryption.Version = EncryptionVersion.Agile;
    m_Excel.Encryption.Algorithm = EncryptionAlgorithm.AES256;
}


Thanks

Alan

**Comment by SpooRancher** [comment]
[Test2.xlsx](https://github.com/JanKallman/EPPlus/files/1771504/Test2.xlsx)

**Comment by JanKallman** [comment]
Fixed in 4.5.1
