### ISSUE TITLE
Double quotes for text in csv LoadFromText is leaving quote in last csv column

### ISSUE THREAD

**Issue by gthelp** [JanKallman/EPPlus#178]
**CSV** 
"BillingMonth","SequenceNumber","Level7Code"
"022018","1",""

**Code**
using (ExcelPackage package = new ExcelPackage())
            {
var sheet = package.Workbook.Worksheets.Add("TestData");
var format = new ExcelTextFormat();
format.TextQualifier = '"';
var range = sheet.Cells["A1"].LoadFromText(filePath, format, TableStyles.None, true);
sheet.View.ShowGridLines = false;
            sheet.Calculate();
            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();

package.SaveAs(newFile);
}

**Results** - leaves double quote at end of last column
BillingMonth | SequenceNumber | Level7Code
022018 | 1 | " 

For now, I check last column and manually remove them
int totalCols = sheet.Dimension.Columns;
            int totalRows = sheet.Dimension.Rows;
            var emptyCells =
                from cell in sheet.Cells[1,totalCols, totalRows, totalCols]
                where cell.Value?.ToString() == "\""
                select cell;

            foreach (var excelCell in emptyCells)
            {
                try
                {
                    excelCell.Value = "";
                }
                catch (Exception) { }
            }

**Comment by GeertVeenstra** [comment]
This bugfix is giving me problems in my application.
I am getting an exception in (only) the last line of my .csv file.
Previous lines are processed ok.

System.Exception: Text delimiter is not closed in line : "NAME";"103";"";"";"";"1977-01-01 00:00:00";"2029-12-31 00:00:00";"1";"1";"210";"NAME (210)";"000210";"1977-01-01 00:00:00";"2029-12-31 00:00:00";"1";"101";"1";"";"";"1"

**Comment by JanKallman** [comment]
Fixed in 4.5.2
