### ISSUE TITLE
EPPlus corrupts the file when set workbook properties (for specific template) 

### ISSUE THREAD

**Issue by stevenxi** [JanKallman/EPPlus#181]
Use EPPlus to open a template Excel file, update workbook property. Save the result as a new file.
Open the new file with Excel, Excel warns the "We found a problem with some content....".
(Excel opens the original template without problem)

Code as below, template file attached.

             var fi = new FileInfo(@"Template.xlsx");
            using (var pck = new ExcelPackage(new FileInfo(@"Template_Result.xlsx"), fi))
            {
                pck.Workbook.Properties.Author = "X";
                pck.Save();
            }

[Template.xlsx](https://github.com/JanKallman/EPPlus/files/1889031/Template.xlsx)

**Comment by stevenxi** [comment]
Did a further investigation, issue is EPPlus added a custom-property xml file  reference in the XML"/docProps/custom.xml". But the file does not actually exist.

**Comment by JanKallman** [comment]
The properties got corrupted if some of the custom properties was left out. Fix added.

**Comment by JanKallman** [comment]
Fixed in 4.5.2
