### ISSUE TITLE
In ExcelPackage CloseStream() results in System.ObjectDisposedException: Cannot access a closed Stream.

### ISSUE THREAD

**Issue by KarlZ** [JanKallman/EPPlus#184]
[EPPlus 45 Issue.zip](https://github.com/JanKallman/EPPlus/files/1900777/EPPlus.45.Issue.zip)<br/>
Our use of 4.1.1 for creating a spreadsheet and downloading it from an MVC controller action was to have the action return a `FileStreamResult` based on a new `MemoryStream` that was passed into the `ExcelPackage(stream)` contructor. In 4.5.1, code was added (`CloseStream()`) that disposes of that stream while 4.1.1 would preserve it if `IsExternalStream` was true (which it was set to true in that constructor if the `stream.Length == 0`.)<br/>
We found a workaround, but this might trip a lot of web people up, since this was a recommended way to do this.<br/>
I've attached a fairly small solution that has 4 projects:<br/>
1. WebApplicationOn41<br/>
2. WebApplicationOn45<br/>
3. WebApplicationOn41.Tests (with one test)<br/>
4. WebApplicationOn45.Tests (with two tests, including the failing one).<br/>

You can see that a unit test in the 45 tests that tries to use the original pattern fails with the `ObjectDisposedException`.<br/>
Let me know if you have questions.<br/>

KarlZ

**Comment by KarlZ** [comment]
**Workaround**
If others run into this issue where the External stream is disposed and thus not usable after disposing of the ExcelPackage, you can do this - Don't pass the stream into the constructor:<br/>
`var stream = new MemoryStream();`<br/>
`using (var excelPackage = new ExcelPackage())`<br/>
`{`<br/>
`   … do EPPlus magic here …`<br/>
`   excelPackage.SaveAs(stream);`<br/>
`}`<br/>
<br/>
rather than:<br/>
`var stream = new MemoryStream();`<br/>
`using (var excelPackage = new ExcelPackage(stream))`<br/>
`{`<br/>
`   … do EPPlus magic here …`<br/>
`   excelPackage.SaveAs(stream);`<br/>
`}`<br/>

**Comment by KarlZ** [comment]
In addition to having the example solution, I added a pull request (#187 ) that will hopefully make reviewing this easier.

**Comment by JanKallman** [comment]
Thanks for reporting this. I will provide a new version fixing this bug, hopfully in a few days.

**Comment by JanKallman** [comment]
Should be fixed now
