### ISSUE TITLE
Thank you so much for this wonderful tool Jan and Co.

### ISSUE THREAD

**Issue by Saad-Alothman** [JanKallman/EPPlus#190]
this is not an issue, just i want to say thank you for this Super helpful tool that i would gladly be paying for it! maybe there should be an enterprise/pro edition.

Jan and the rest thank you all from all my heart.

sorry if this is not the right place to say thanks.

im really busy at the moment like everyone else is, but i wanted to say what i said.

Saad,

**Comment by JanKallman** [comment]
Thanks, allways nice with some positive feedback!
