### ISSUE TITLE
AutoFitColumns() is too slow for large .xlsx files

### ISSUE THREAD

**Issue by slycoderr** [JanKallman/EPPlus#191]
I generate an xlsx file that has around 8 sheets with each sheet having 10,000 to 40,000 rows and between 10 to 40 columns each sheet.  When calling `sheet.Cells[sheet.Dimension.Address].AutoFitColumns();`, on each sheet it takes 1 minute just to execute this method for all the sheets. Is there a way I can fit the columns faster?

**Comment by slycoderr** [comment]
The algorithm I created below is 77% faster than the method you are doing in `public void AutoFitColumns(double MinimumWidth, double MaximumWidth)` in ExcelRangeBase.cs.

          
`Font stringFont = new Font("Calibri", 11);`
`var b = new Bitmap(1, 1);`
`var g = Graphics.FromImage(b);`
`g.PageUnit = GraphicsUnit.Pixel;`

            foreach (var sheet in package.Workbook.Worksheets)
            {
                //find the longest string in each column, measure it, then set its width to the column
                for (int i = 1; i < sheet.Dimension.Columns; i++)
                {
                    var longestString = "";
                    var name = GetExcelColumnName(i);

                    foreach (var c in sheet.Cells[($"{name}:{name}")])
                    {
                        longestString = c.Text.Length > longestString.Length ? c.Text : longestString;
                    }
                    var stringSize = g.MeasureString(longestString, stringFont, 10000);

                    sheet.Column(i).Width = stringSize.Width;
                }
            }
`

**Comment by richardtallent** [comment]
`AutoFitColumns()` actually has to call the GDI `MeasureString()` function for every cell in the worksheet, using that cell's chosen font/style/indent/etc. This is a fast function, but the calls can add up.

Four possible options for you:

1. Use a different range, say, the first 500 rows of each sheet. That would be a 20x-80x decrease in computation effort, and provided the first 500 rows are fairly representative of the whole, the result would be about the same.

2. Create a macro that runs when the spreadsheet opens, and use Excel's native functionality to auto-set the widths of the active range on each sheet.

3. Ignore the AutoFitColumns function, and create your own algorithm to estimate the correct width of each column based on the longest string. This won't be an exact science, but might be close enough for your application.

4. There are two optimizations I think could be made to the code here. I don't know if Jan would agree, but it should make for an easy PR:

https://github.com/JanKallman/EPPlus/blob/8ab7d73a0a87979d15c1cec285c7bfcf6b9aeead/EPPlus/ExcelRangeBase.cs#L909

The first optimization would be to use a Dictionary to cache the widths of distinct values in a given font/style. I know for my own spreadsheets at least, there are a lot of repeated values. The second would be to *not* measure any string that is, say, less than 1/3 the length of the longest string measured so far in the column. This might not catch some edge cases, but could be much faster if the formatted values vary widely in a given column.

**Comment by slycoderr** [comment]
Yeah I basically ended up doing 3. I just looped through the column , found the longest string and measured it, then set the width. My spread sheet is the same font so there's no need to measure every cell. This changed the time from 1 minute to 18 seconds.

**Comment by Seabizkit** [comment]
@slycoderr can you share the code that you used please, to do the above
