### ISSUE TITLE
Bug when merge excel files after adding image from stream

### ISSUE THREAD

**Issue by jiemon** [JanKallman/EPPlus#193]
When I add image via AddPicture from Image

```
var img = Image.FromStream(ms);
var picture = ws.Drawings.AddPicture($"test.jpeg", img);
```
and after that I try copy sheet with this image somewhere
I get exception System.NullReferenceException: 'Object reference not set to an instance of an object.'
at line 189 in EPPlus.Core/src/EPPlus.Core/Drawing/ExcelPicture.cs
`switch (contentType.ToLower(CultureInfo.InvariantCulture))`

contentType for ExcelPicture always is null when it added not from File

**Comment by JanKallman** [comment]
This seams to be EPPlus.Core. Please use latest version of EPPlus.
