### ISSUE TITLE
Can’t get custom date format to only display the day of the month

### ISSUE THREAD

**Issue by flindr** [JanKallman/EPPlus#196]
I have a date 1/1/2018 and I want it displayed as just 1. I set the custom formatting type to just ‘d’.
In Excel it is displayed as it should but when I read the cell.Text property it’s set to 1/1/2018. If I set the type to ‘dd’ it is displayed as 01, 02 etc. Correctly as it should.
I tried in OpenOffice to set the format ‘d’ and it works there (OpenOffice API is used in Epplus right?)

Repro steps:
1.	Load the attached file with Epplus.
2.	Read cells B2 (format ‘d’) and C2 (format ‘dd’).
3.	Text property on cell B2 will read 01/01/2018 but should be 1.
4.	Text property on cell C2 will read 01 as it should be.

Edit: Excel file is attached.

![image](https://user-images.githubusercontent.com/17991532/39127522-93198ce0-4705-11e8-8478-fd52a424c1df.png)

![image](https://user-images.githubusercontent.com/17991532/39127529-964f7c4e-4705-11e8-947e-6c7b45a46ad3.png)

[dateformatbug.xlsx](https://github.com/JanKallman/EPPlus/files/1938232/dateformatbug.xlsx)

**Comment by JanKallman** [comment]
d was incorrectly transformed as the shortdate format (in .NET). The problem should now be fixed. 
EPPlus don't us the ooxml sdk.

**Comment by JanKallman** [comment]
Yes, it should be fixed now in version 4.5.2. We have some problem with appveyor at the moment.
