### ISSUE TITLE
Bug when generating more than 65536 hyperlink rows

### ISSUE THREAD

**Issue by sebascomeau** [JanKallman/EPPlus#199]
When generating many rows with a column containing hypelinks, Excel finds unreadable content when opening the file. Excel need to recover the file and removes all the hyperlinks.

If I choose to generate a file with less than 65000 rows it works fine.

This issues was found in 2015 and marked has a bug in codeplex #14949.

**Comment by vadim82** [comment]
I have experienced the same thing. Even with less rows. I think it may be because of the number of hyperlinks in the the file and not so much rows.

**Comment by JanKallman** [comment]
This is a limitation in Excel, so thats why you get the error. See [here](https://support.office.com/en-us/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3). I think this is unique hyperlinks, so i'm note sure if this is an easy fix (to throw a more informative exception).
