### ISSUE TITLE
FormatException error when using Calculate() with a spreadsheet containing VALUE function

### ISSUE THREAD

**Issue by ImapDev** [JanKallman/EPPlus#209]
When calling Workbook.Calculate() for a spreadsheet containing a cell with the VALUE function, we get a FormatException error. This seems to happen where the VALUE function references a blank or empty cell.

eg having a cell with formula =VALUE(A1) where A1 is blank or empty, then calling Calculate() causes this exception.

Expected behaviour - Excel seems to evaluate this situation as returning 0, so I think VALUE should return 0 where A1 is blank or empty.

**Comment by swmal** [comment]
Fixed in latest source.
