### ISSUE TITLE
Getting started example code doesn't compile

### ISSUE THREAD

**Issue by roelfveldhuis** [JanKallman/EPPlus#21]
In the first example code of the Getting Started page on the wiki:

`ws.Cells["A1"] = "This is cell A1";`

This doesn't compile: Property or indexer 'ExcelRange.this[string]' cannot be assigned to -- it is read only
Maybe instead it should read:

`ws.Cells["A1"].Value = "This is cell A1";`

I'm not sure though, because I'm just Getting Started with the library.

**Comment by JanKallman** [comment]
Sorry about that, I have changed it. Thanks for reporting it
