### ISSUE TITLE
Apostrophe in Worksheet Name Causes Issue When Accessing Workbook Property

### ISSUE THREAD

**Issue by onslaughtq** [JanKallman/EPPlus#219]
I'm having an issue, after upgrading from 4.1.1 to 4.5.2, with worksheet names that have an apostrophe in them.  Prior to the upgrade, I could access those sheets just fine, but after the upgrade, I get an error with the following stack trace:

at OfficeOpenXml.ExcelRangeBase..ctor(ExcelWorksheet xlWorksheet, String address)
at OfficeOpenXml.ExcelNamedRangeCollection.Add(String Name, ExcelRangeBase Range)
at OfficeOpenXml.ExcelWorkbook.GetDefinedNames()
at OfficeOpenXml.ExcelPackage.get_Workbook()

I've attached a sample Visual Studio console application, with both a good example containing no apostrophes, and a bad file with the apostrophes still present.

The issue occurs in .Net Core application as well as .Net Framework applications.

[EPPlusIssue.zip](https://github.com/JanKallman/EPPlus/files/2049871/EPPlusIssue.zip)

**Comment by JanKallman** [comment]
Fixed in 4.5.2.1
