### ISSUE TITLE
EPPlus, Linux, .Net Core

### ISSUE THREAD

**Issue by coremanster** [JanKallman/EPPlus#224]
Here's what I did...  EPPlus can work in Powershell 6/.Net Core on Linux now too.

I've done the instructions from Microsoft to install latest versions of Powershell 6 & .Net Core Framework on my linux box.

So... pwsh works.

PS >$PSVersionTable.Name

6.1.0-preview.2

I installed VS Code to try and build from source... but that wasn't working so well for me. 

So I installed the nuget package manager into VS Code.
Then, I used nuget to install EPPlus.Core, in the folder I want EPPlus to be in (~/EPPlus)

first, though, need this dependency loaded first:

nuget install CoreCompat.System.Drawing -version 1.0.0-beta006

...then this will work:

nuget install EPPlus.Core

To reference the EPPlus.Core dll in Powershell:

###myfirstepplus.ps1

add-type -Assembly ~/EPPlus/EPPlus.Core.1.5.4/lib/net40/EPPlus.Core.dll
$xl = new-object OfficeOpenXml.ExcelPackage$wb = $xl.Workbook$ws = $wb.Worksheets.Add("Sheet100")$ws.Cells["A1"].Value = 123$ws.Cells["zz2234"].Value = 321$r = $ws.Dimension.End.Row$c = $ws.Dimension.End.Column
write-output "rows: $r`tcols: $c"
$xl.SaveAs("./epplus.xlsx")

then I run my .ps1 file by "dot-sourcing" it in pwsh:

PS > ./myfirstepplus.ps1

rows: 2234      cols: 702

I can then open the excel file in LibreOffice or whatever to verify that it worked and doing Ctrl+End to go to the last cell on the worksheet... 

Wish I could build it from source, but...this works.

**Comment by andrericardo** [comment]
In https://www.nuget.org/packages/EPPlus/ says
```
    .NET Core uses a preview of System.Drawing.Common, so be aware of that. We will update it as Microsoft releases newer versions.
     System.Drawing.Common requires libgdiplus to be installed on non-Windows operating systems.
     Use your favorite package manager to install it.
     For example:

     Homebrew on MacOS:
     brew install mono-libgdiplus

     apt-get:
     apt-get install libgdiplus
```
Maybe installing libgdiplus would help?

**Comment by mi-hol** [comment]
As of 5Aug2018 
sudo nuget install EPPlus.Core
fails with errors permanently

on first attempt error was;
Attempting to resolve dependency 'NETStandard.Library (≥ 1.6.1)'.
'NETStandard.Library' already has a dependency defined for 'Microsoft.NETCore.Platforms'.

tried;
sudo nuget install Microsoft.NETCore.Platforms
The 'Microsoft.NETCore.Platforms 2.1.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.7.0'.

fixed via:
sudo nuget update -self
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 2.8.7.
Updating NuGet.exe to 4.6.2.
Update successful.

but then;
mihol@W10D-RS4:~$ sudo nuget install EPPlus.Core
Could not load file or assembly or one of its dependencies.
  Could not load file or assembly or one of its dependencies.
  Could not load file or assembly or one of its dependencies.
  Could not load file or assembly or one of its dependencies.
  Could not load file or assembly or one of its dependencies.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
   --- End of inner exception stack trace ---
  at NuGet.CommandLine.Program.Initialize (NuGet.IFileSystem fileSystem, NuGet.CommandLine.IConsole console) [0x000ce] in <36d8eef4280843bbad2e04b497b5fab0>:0
  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) [0x000e3] in <36d8eef4280843bbad2e04b497b5fab0>:0
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'<---

---> (Inner Exception #1) System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'<---

---> (Inner Exception #2) System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'<---

---> (Inner Exception #3) System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'<---

---> (Inner Exception #4) System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'<---

**Comment by mi-hol** [comment]
could be related to https://github.com/dotnet/corefx/issues/31449

**Comment by mi-hol** [comment]
Applying the certificate as documented in https://github.com/mono/mono/issues/9891
and updating mono, allowed it to work again :)

````
Setting up libmono-system-servicemodel4.0a-cil (5.14.0.177-0xamarin3+ubuntu1804b1) ...
Setting up nuget (4.7.0.5148.bin-0xamarin2+ubuntu1804b1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
mihol@W10D-RS4:~$ nuget install EPPlus.Core
Feeds used:
  https://api.nuget.org/v3/index.json

Installing package 'EPPlus.Core' to '/home/mihol'.
  GET https://api.nuget.org/v3/registration3-gz-semver2/epplus.core/index.json
  OK https://api.nuget.org/v3/registration3-gz-semver2/epplus.core/index.json 581ms


Attempting to gather dependency information for package 'EPPlus.Core.1.5.4' with respect to project '/home/mihol', targeting 'Any,Version=v0.0'
Gathering dependency information took 36.35 ms
Attempting to resolve dependencies for package 'EPPlus.Core.1.5.4' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'EPPlus.Core.1.5.4'
Resolved actions to install package 'EPPlus.Core.1.5.4'
Retrieving package 'EPPlus.Core 1.5.4' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/epplus.core/1.5.4/epplus.core.1.5.4.nupkg
  OK https://api.nuget.org/v3-flatcontainer/epplus.core/1.5.4/epplus.core.1.5.4.nupkg 32ms
Installing EPPlus.Core 1.5.4.
Adding package 'EPPlus.Core.1.5.4' to folder '/home/mihol'
Added package 'EPPlus.Core.1.5.4' to folder '/home/mihol'
Successfully installed 'EPPlus.Core 1.5.4' to /home/mihol
Executing nuget actions took 3.78 sec
````

**Comment by mi-hol** [comment]
running it inside pwsh works too!!

````
PS /home/mihol> add-type -Assembly ~/EPPlus.Core.1.5.4/lib/net40/EPPlus.Core.dll
PS /home/mihol> $xl = new-object OfficeOpenXml.ExcelPackage
PS /home/mihol> $wb = $xl.Workbook
PS /home/mihol> $ws = $wb.Worksheets.Add("Sheet100")
PS /home/mihol> $ws.Cells["A1"].Value = 123
PS /home/mihol> $ws.Cells["zz2234"].Value = 321
PS /home/mihol> $r = $ws.Dimension.End.Row
PS /home/mihol> $c = $ws.Dimension.End.Column
PS /home/mihol> write-output "rows: $r`tcols: $c"
rows: 2234      cols: 702
PS /home/mihol> $xl.SaveAs("./epplus.xlsx")
PS /home/mihol> ls
EPPlus.Core.1.5.4  epplus.xlsx  ftp
````

**Comment by mi-hol** [comment]
https://github.com/dfinke/ImportExcel/issues/150

**Comment by mi-hol** [comment]
A recent Microsoft blog article [on cross platform support](https://blogs.msdn.microsoft.com/powershell/2018/08/06/powershell-standard-library-build-single-module-that-works-across-windows-powershell-and-powershell-core/) seems relevant 
"NuGet package PowerShellStandard Library 5.1.0. This package allows developers to create modules that are portable between Windows PowerShell 5.1 and PowerShell Core 6.0. This means that you can create PowerShell modules that run on Windows, Linux, and macOS with a single binary!"

**Comment by swmal** [comment]
It seems like you are using EPPlus.Core which is an unofficial port of EPPlus for .NET core from the time when the official EPPlus did not support it. It is not maintained by us.
