### ISSUE TITLE
Contribution to EPPLUS

### ISSUE THREAD

**Issue by dokkillo** [JanKallman/EPPlus#24]
Hi, I'm C# developer, I use this DLL a lot and really I would like to help coding or something, but I'm trying to find any documentation about how to help, and I don't find nothing.

Is possible any documentation (word etc..) about the architecture of project? or anything else?

Sorry for use an issue for it, but its the only way to communicate that I find.

Regards

**Comment by AkosLukacs** [comment]
I'm just about to pull the source, and see if it builds

**Comment by dokkillo** [comment]
Yes, its the first thing that I did, but some parts of the code are a bit hard (not imposible, just hard ) and if Epplus have some documentation, maybe understand epplus code will be a bit more easy hehe...

**Comment by swmal** [comment]
What we currently have is the comments/docs in the code and the github wiki. The only advise I can give is to start looking at the code from the ExcelPackage class.

**Comment by zippy1981** [comment]
@dokkillo Can I suggest adding unit tests to uncovered classes? You might uncover bugs that way, and you will learn the code.
