### ISSUE TITLE
can not operand "+=" cells of sheets in epplus

### ISSUE THREAD

**Issue by wahedfazeli** [JanKallman/EPPlus#243]
nevertheless i change all cells of sheets in **epplus** to double sheets,but the error operand += happen in my code.this is my code.

     sheet.Cells["C1:C"+sheet.Dimension.Rows].Style.Numberformat.Format = "0";
                //sheet.Cells["C1:C" + sheet.Dimension.Rows].Value = s;
                for (int x = 1; x <= sheet2.Dimension.Rows; x++)
                {
                    for (int y = 1; y <= sheet.Dimension.Rows; y++)
                    {
                        if (sheet.Cells[y, 1].Value.ToString() != null)
                        {
                            if (sheet2.Cells[x, 1].Value.Equals(sheet.Cells[y, 1].Value.ToString()))
                            {
                                sheet2.Cells[x, 4].Value.GetType<Double>() += sheet.Cells[y, 3].Value.GetType<Double>();

                            }
                        }
                    }
                }

**Comment by swmal** [comment]
You can't do it like that, it is not an EPPlus issue but rather how c#/.net works.  You can instead read the value, put it into a local variable, apply the += and then write it back.
