### ISSUE TITLE
Adding pivot table results in corrupt xlsx when constructing ExcelPackage with existing office 2016 file

### ISSUE THREAD

**Issue by JasperE84** [JanKallman/EPPlus#25]
Hi there,
I noticed EPPlus creates corrupt excel files when starting from an existing Excel template.

Steps to reproduce

- Install latest office 365 (office 2016) 

- I am using: 1705 (Build 8201.2193 CLick-to-Run) / Deferred Channel

- Create folder c:\temp

- Right click in windows explorer in c:\temp empty space, New file -> Microsoft Excel file

- Name file "template.xlsx"
Here is  the blank file I then get:
[template.xlsx](https://github.com/JanKallman/EPPlus/files/1364387/template.xlsx)

- Modify Sample12.cs as following:

```
string fileInput = @"c:\temp\template.xlsx";
string fileOutput = @"c:\temp\output.xlsx";
File.Copy(fileInput, fileOutput);
FileInfo newFile = new FileInfo(fileOutput);
using (ExcelPackage pck = new ExcelPackage(newFile))
{
<snip>
pck.Save();
}
return fileOutput;
```

- Run sample application

- Try to open c:\temp\output.xlsx

- Excel will say file is corrupted
Here is the corrupt file I'm getting
[output.xlsx](https://github.com/JanKallman/EPPlus/files/1364390/output.xlsx)

Workaround:

- Take Sample12.xlsx from the default sample app without modifications
- Copy the worksheets from your Excel 2016 template to the Sample12.xlsx file
- Save using Excel
- Use that as your new template

**Comment by JanKallman** [comment]
This is fixed in 4.5.1
