### ISSUE TITLE
Rounding problems

### ISSUE THREAD

**Issue by bschlindwein** [JanKallman/EPPlus#292]
When I use the "ROUND" function in an Excel sheet, a".5" value is rounded down.
Is it possible to overload the function like the "Math.Round" function so that it is possible to select whether to round up or down?

**Comment by swmal** [comment]
Yes, you can always replace the built in function in EPPlus with your own implementation.

https://github.com/JanKallman/EPPlus/wiki/Implementing-missing-or-new-Excel-functions

/Mats
