### ISSUE TITLE
Bug: SUMIFS not working when set the row criteria ranges

### ISSUE THREAD

**Issue by Sungil0916** [JanKallman/EPPlus#297]
When I tried to execute the SUMIFS function in my project, I got a #VALUE! issue with the cells in relation to SUMIFS functions. So, I tried to figure out what is the problem. Then, I find out that SUMIFS function does not work with ""row criteria ranges". 

Please let me know how to fix this issue.
Thank you!

**Comment by swmal** [comment]
Please provide a more extensive description of the error, with examples containing enough information to reproduce.
