### ISSUE TITLE
Main LICENSE question - conflicting information found in README.md vs LICENSE files

### ISSUE THREAD

**Issue by juliaszegedi** [JanKallman/EPPlus#311]
Hello! 

I am writing regarding the global license of this component, EPPlus version 4.5.1. In the LICENSE file we have the Lesser General Public License version 3 enlisted, whereas the README.md file says that the project is licensed under the GNU Library General Public License. More confusing is the fact that in lots of files there are references about the GNU Lesser General Public License v2.1 or later. 

Could you please help me by clarifying this licensing issue? 
Lots of thanks in advance!

Best regards,
Julia

**Comment by swmal** [comment]
Hi Julia,

There is obviously a cleaning job that needs to happen. We switched to lgpl a while ago, you can find a value link on the EPPlus nuget page.

https://www.gnu.org/licenses/lgpl-3.0.en.html

/Mats

/Mats

**Comment by juliaszegedi** [comment]
Thanks a lot! 

Julia

**Comment by Alex-Vaduva** [comment]
Hi Mats,

When did you switch to LGPL-3.0? I'm interested in the 4.0.4 version which hasn't any license or readme files and only GNU Lesser General Public License v2.1 or later references. Is LGPL-2.1 or later the main license of the specified version?

Thanks,
Alex.

**Comment by swmal** [comment]
Hi Alex,

The LGPL version changed from 2.1 to 3.0 at EPPlus 4.1.1, so 4.0.4 is LGPL 2.1.

Regards,

Mats

Sent from my iPhone
