### ISSUE TITLE
Opening an Excel file and then trying to save it without modifications fails in package.SaveAs()

### ISSUE THREAD

**Issue by pdavis68** [JanKallman/EPPlus#312]
I'm having an odd issue that I don't know how to resolve. The following terse example demonstrates the problem:

    using (Excel.ExcelPackage package = new Excel.ExcelPackage())
    {
        using (Stream s = File.OpenRead(@"c:\temp\Temp.xlsx"))
        {
            package.Load(s);
        }
        // ************************************
        // Remove this section and it works
        using (Excel.ExcelWorkbook wb = package.Workbook)
        {

        }
        // ************************************
        using (MemoryStream ms = new MemoryStream())
        {
            package.SaveAs(ms);
            File.WriteAllBytes(@"c:\temp\Temp2.xlsx", ms.GetBuffer());
        }
    }

The "Temp.xlsx" file, I suppose can be anything. I just right clicked in explorer and created a blank xlsx file (which was 7K in size, so clearly not completely empty).

If you remove the inner "using" referencing the workbook, you won't have an issue.

**Comment by pdavis68** [comment]
It appears that I need to save it before disposing of the Workbook.

**Comment by binki** [comment]
I would be surprised if it made sense to do `using (var something = myObject.Property){}` ever. Normally, the lifetime of objects which are exposed as properties on existing objects is already under the control of another object. For example, when `package` is disposed, it will automatically take care of `package.Workbook` as can be seen here: https://github.com/JanKallman/EPPlus/blob/d30625029c909250938a80f3a1c86844a8aaa151/EPPlus/ExcelPackage.cs#L810 .

So, I would consider it *normally likely to be incorrect* to `Dispose()` objects that don’t come from something like a method call with `Create` or `Build` or `Open` in its name or which you construct yourself. For example, if the object returned by something like `myObject.CreateInstance()` implements `IDisposable`, it is very likely that that means **your code** owns the lifetime of that object and in fact **must** use `using(){}` or `.Dispose()`. The same with `new ExcelPackage()`—you correctly placed a `using` there.
