### ISSUE TITLE
Spreadsheet to HTML

### ISSUE THREAD

**Issue by SuperDaveWhite** [JanKallman/EPPlus#316]
I have a dataset that I have been turning into a spreadsheet for years with EPPlus, but I now need it as HTML to drop into a Shoppify webpage. What is the best way to migrate the spreadsheet I have now out to HTML?

The only suggestion so far is pretty poor and that is to "upload it to Google Sheets, then make it public and grab the embed code, and paste that into a Hypervisual custom HTML section".

Is there anything I am missing in EPPlus that would make this easier.

**Comment by swmal** [comment]
There is currently no such feature in EPPlus.
