### ISSUE TITLE
Add link to API docs in Wiki

### ISSUE THREAD

**Issue by hansfn** [JanKallman/EPPlus#318]
On http://www.nudoq.org/#!/Packages/EPPlus there seems to be proper API docs for EPPPlus (generated from the source). If we don't have any better sources, I think this should be listed prominently on the wiki.

PS! I have contacted the  nudoq.org people asking for an update as it's for version 3.1.3.

**Comment by swmal** [comment]
I am not too familiar with nudoq, but had a quick look and more libraries than EPPlus are documented referencing older versions. Please let us know in a new issue if they reply.

Thanks.
