### ISSUE TITLE
one small issue, another possible

### ISSUE THREAD

**Issue by rdenxx** [JanKallman/EPPlus#319]
1. copying a range of cells that includes merged cells works, however copying a range of cells that equals the merged cell range didn't.

Simple fix, in: ExcelRangeBase.cs, within the method void Copy(...)
_somewhere around line 2618 - 7 lines below // Merged Cells comment_
The line that reads as:

    if (this.Collide(adr) == eAddressCollition.Inside)

change to:

    if (this.Collide(adr) == eAddressCollition.Inside || this.Collide(adr) == eAddressCollition.Equal)

(if the Collide operation is expensive may be better to call it once storing into a local var and compare that to the 2 options.)

2. applyAlignment in styles.xml - my thought is not an EPPlus bug per se, but for compatibility sake worth the workaround.

Background: saved a sheet in EPPlus that rendered correctly in Excel, but same document rendered wrong in LibreOffice - alignments were wrong.
Chased the issue down to styles.xml in the cellXfs section: when alignment is set in a cellXfs element (i.e. non default) files saved from excel include `"applyAlignment="true"`, those saved from EPPlus don't include that.
_Strangely Excel still renders the EPPlus saved file correctly, (I guess Excel default applyAlignment must be true.)  LO doesn't, (so I guess it's default is false / 0)_

So not strictly a bug (?), regardless needed to get work done compatibile between different users...  the following patch [in my own copy] solved the issue:
EEPlus/epplus/style/XmlAccess/ExcelFillXml.cs in method CreateXmlNode(...) near the bottom of the method

    if ((_horizontalAlignment != ExcelHorizontalAlignment.General || _verticalAlignment != ExcelVerticalAlignment.Bottom) && doSetXfId)
    {
            SetXmlNodeString("@applyAlignment", "1");  
    }

**Comment by JanKallman** [comment]
Thanks, applied changes

**Comment by pucis** [comment]
Similar to PR: https://github.com/JanKallman/EPPlus/pull/62
This only fixes horizontal/vertical alignment.
Can you please create a fix for textRotation/wrapText/shrinkToFit.
