### ISSUE TITLE
Error opening the file after copying worksheet and copying ranges

### ISSUE THREAD

**Issue by rashuf** [JanKallman/EPPlus#32]
Error opening the file after copying worksheet and copying ranges
Hello!
I found some problem whit coping ranges. Problem is:
 
1. I copy worksheet 
2. I copy ranges from one worksheet to copied worksheet. 

If in copied ranges have merged cells, when I open the file in Excel, Excel tells me 
"Excel found unreadable content in sample1_copied.xlsx. Do you want to recover the contents of this workbook? 
If you trust the source of this workbook, 
click Yes." 

After I click Yes, I see message "Removed Records: Merge cells from /xl/worksheets/sheet2.xml part" (v. 4.5.0) 
and also "Removed Records: Shared formula from /xl/worksheets/sheet2.xml part" (v. 4.1.1)
Test code: Sample1_copyWorksheet
Source/input file: sample.xlsx
Result/output file: sample1_copied.xlsx

PS: if I run the method package.save and reopen the file between copying worksheet and ranges, it works.
[Sample1_CopyWorksheet.zip](https://github.com/JanKallman/EPPlus/files/1389869/Sample1_CopyWorksheet.zip)

**Comment by JanKallman** [comment]
Fixed in. 4.5.1

**Comment by pinnahari** [comment]
I am getting this error in version : 4.5.1.0 ,v4.0.30319 : v4.0.30319. I am trying to fill the excel sheet (using template), getting error while opening the file. Thanks.

**Comment by DiogoMoreira0610** [comment]
I'm getting same error on v4.3.5. Can you help?

**Comment by melkor54248** [comment]
Same for me.
