### ISSUE TITLE
Fail To Insert Image on Linux

### ISSUE THREAD

**Issue by zy0421911** [JanKallman/EPPlus#322]
Fail To Insert Image on Linux (.net core 2.1) because    gdi+ can not get  the   Image.HorizontalResolution and Image.VerticalResolution  correctly , so  it  returns 0.   I hope you will repair this problem. Thank you.

**Comment by swmal** [comment]
We will update System.Drawing to the latest version from Microsoft in the next release, let's hope that will resolve your problem.
