### ISSUE TITLE
Public review of the revision draft of Open Packaging Conventions of OOXML (ISO/IEC 29500-2)

### ISSUE THREAD

**Issue by murata2makoto** [JanKallman/EPPlus#338]
Allow me to post this issue, although it is not a bug report or feature request.  I am the convenor of an ISO committee (ISO/IEC JTC1/SC34/WG4), which maintains OOXML (ISO/IEC 29500).

We are revising Open Packaging Conventions of OOXML (ISO/IEC 29500-2) very thoroughly.  The biggest motivation for this revision is to address issues around part names, references, pack URIs, base URIs, resolution of relative references, and non-ASCII characters.  We are aware that lack of clarity in the currently published ISO/IEC 29500-2 has caused interoperability problems.

We hope that this revision helps implementations including EPPLUS and that it does not cause any troubles.  But we are not 100% sure.

We are thus very interested in feedback from you.  We have a public review and an open teleconference.  More about this, see [our wiki page](https://github.com/sc34wg4/opcRevision/wiki/Public-review-of-a-working-draft-for-the-revision-of-ISO-IEC-29500-2-(Open-Packaging-Conventions)).

Thanks!

Regards,
Makoto (ISO/IEC JTC1/SC34/WG4 convenor)

**Comment by JanKallman** [comment]
Thanks for letting us know. We haven't had any issues with the mentioned functionality lately, so I don't think we have much feedback. We had some issues with the ASCII encoding in earlier versions, but nothing that was related to the OOXML documentation. Is there anything in particular you want me to look at that could affect EPPlus? 
Thanks Jan

**Comment by murata2makoto** [comment]
Relative references from relationships parts to other parts might begin with "/" or might not.  Such relative references have to be resolved differently.  Does EPPlus support both?
