### ISSUE TITLE
Row and Column numbers for a cell

### ISSUE THREAD

**Issue by JamesFenton** [JanKallman/EPPlus#340]
There doesn't seem to be a way to get the row and column number for a cell.

```
var package = new ExcelPackage(stream);
var worksheet = package.Workbook.Worksheets["Sheet1"];
var cell = worksheet.Cells["C7"];
cell.Address; // "C7"
var rowNumber = cell.Row; // doesn't exist - should return 7
var columnNumber = cell.Column; // doesn't exist - should return 3
```

If you were looping through the cells in the worksheet, it is possible, but annoying. The `cell.Address` property is a string, but in the ClosedXML library it is an object that has properties like: `ColumnLetter`, `ColumnNumber`, `RowNumber`

**Comment by mclean25** [comment]
Hi @JamesFenton,

What you can do is:

```
cell.Start.Row // 7
cell.Start.Column // 3
```

Reason for using `Start` is that cells are effectively ranges. Take `B7:C7`:
```
cell.Start.Row // 7
cell.Start.Column // 2
cell.End.Row // 7
cell.End.Column // 3
```

**Comment by JamesFenton** [comment]
Oh great, thanks
