### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by monty241** [JanKallman/EPPlus#346]
Last version available on nuget.org is 4.5.2.1.

4.5.2.1 does not include the NullReference fix included in e7230ed0450ff9985b4c8a159f74ca1c348d6e67 for #234 .

Today ran into this problem in production situation, but the cause was already fixed. Workaround available.

Would nonetheless be helpful when a new production version on nuget package could be scheduled.

**Comment by swmal** [comment]
We are working on a new version and it will be released soon,
