### ISSUE TITLE
Sorting will not move comments

### ISSUE THREAD

**Issue by spindisc** [JanKallman/EPPlus#349]
When sorting, comments stay at their original cell and are not moved with the cell they belong to. This must be a bug.

`

            using (var xls = new ExcelPackage())
            {
                var ws = xls.Workbook.Worksheets.Add("BUG");

                ws.Cells[1, 1].Value = "DDD";
                ws.Cells[1, 1].AddComment("DDD","ddd");
                ws.Cells[2, 1].Value = "AAA";
                ws.Cells[2, 1].AddComment("AAA", "aaa");
                ws.Cells[3, 1].Value = "CCC";
                ws.Cells[3, 1].AddComment("CCC", "ccc");
                ws.Cells[4, 1].Value = "BBB";
                ws.Cells[4, 1].AddComment("BBB", "bbb");

                ws.Cells[1, 1, 4, 1].Sort(0);
                FileInfo fi = new FileInfo("D:\\Temp\\bug.xlsx");
                xls.SaveAs(fi);
            }

`

**Comment by JanKallman** [comment]
Yes, it's a bug. I will provide a fix shortly

**Comment by JanKallman** [comment]
Fixed in last commit
