### ISSUE TITLE
When inserting at row 1026, the first column isn't shifted down

### ISSUE THREAD

**Issue by igglebop** [JanKallman/EPPlus#351]
When inserting at row 1026, it shifts subsequent rows unevenly.

Before:
![row 1026 before insert](https://user-images.githubusercontent.com/5298672/48973740-e570ba00-effb-11e8-812e-bcfa9676fa1f.png)

After inserting a row:![row 1026 after insert](https://user-images.githubusercontent.com/5298672/48973745-ee618b80-effb-11e8-9a2d-df66d8cf8078.png)

You'd expect the whole row 1026 to shift to row 1027, but instead it shifts unevenly.

The following code illustrates the issue
```c#
using (var package = new ExcelPackage())
{
    // Arrange
    var worksheet = package.Workbook.Worksheets.Add("Test");
    worksheet.Cells[1, 1].Value = "A";                      // If you remove this "anchor", the problem doesn't happen.
    worksheet.Cells[1026, 1].Value = "B";
    worksheet.Cells[1026, 2].Value = "B";
    var range = worksheet.Row(1026);
    range.Style.Fill.PatternType = ExcelFillStyle.Solid;
    range.Style.Fill.BackgroundColor.SetColor(Color.FromArgb(255, 255, 0));

    // Act - This should shift the whole row 1026 down 1
    worksheet.InsertRow(1025, 1);

    // Assert - This value should be null, instead it's "B"
    Assert.IsNull(worksheet.Cells[1026, 1].Value);
}
```

**Comment by JanKallman** [comment]
Fixed in latest commit
