### ISSUE TITLE
Loading Large Data giving Thread aborted error

### ISSUE THREAD

**Issue by ahmadhannan** [JanKallman/EPPlus#355]
While loading Large data here is the result:

- For 50000 rows and 210 columns ... success
- For 50000+ (e.g. 68000) rows and 210 columns ... failing and giving Thread was being aborted error.

**Comment by swmal** [comment]
Hi,

performance related problems are seldom reproducable. We have benchmarked EPPlus with more rows and columns,, but it might depend on the type of content you are inserting and other factors. Please supply a new issue with a unit test that causes this error for you and we will have a look.
