### ISSUE TITLE
Pivot table failure: ":"' ' is an unexpected token. The expected token is ';'

### ISSUE THREAD

**Issue by rekhakumar123** [JanKallman/EPPlus#360]
Pivot table creation gives error. I checked the datarange part for PivotTables.Add api and it looks correct. Not sure what is the error.

Also, is there any limitation on the support for special characters in pivot tables?

Here is the stacktrace:
em.Xml.XmlException","message":"' ' is an unexpected token. The expected token is ';'. Line 1, position 3760.","hasFullStack":true,"parsedStack":[{"level":0,"method":"System.Xml.XmlTextReaderImpl.Throw","assembly":"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":1,"method":"System.Xml.XmlTextReaderImpl.HandleEntityReference","assembly":"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":2,"method":"System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow","assembly":"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":3,"method":"System.Xml.XmlTextReaderImpl.ParseAttributes","assembly":"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":4,"method":"System.Xml.XmlTextReaderImpl.ParseElement","assembly":"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":5,"method":"System.Xml.XmlTextReaderImpl.ParseElementContent","assembly":"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":6,"method":"System.Xml.XmlLoader.LoadNode","assembly":"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":7,"method":"System.Xml.XmlLoader.LoadDocSequence","assembly":"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":8,"method":"System.Xml.XmlDocument.Load","assembly":"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"},{"level":9,"method":"OfficeOpenXml.Table.PivotTable.ExcelPivotCacheDefinition..ctor","assembly":"EPPlus, Version=4.5.1.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1"},{"level":10,"method":"OfficeOpenXml.Table.PivotTable.ExcelPivotTable..ctor","assembly":"EPPlus, Version=4.5.1.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1"},{"level":11,"method":"OfficeOpenXml.Table.PivotTable.ExcelPivotTableCollection.Add","assembly":"EPPlus, Version=4.5.1.0, Culture=neutral,

**Comment by rekhakumar123** [comment]
Isolated the issue. Whenever pivot table input columns have characters that are XML escape characters then above exception happens.
List of xml special characters: 
&
<
"
'

Would EPPPlus support this in future? On excel pivot tables can be created even if these characters are present in the column names.

**Comment by JanKallman** [comment]
Fixed, no encoding when name was set. thanks for reporting it
