### ISSUE TITLE
Issue with Offset function

### ISSUE THREAD

**Issue by zabulus** [JanKallman/EPPlus#368]
[] Write a detailed description of your issue.
Issue with OFFSET function more precisely with ExcelAddressExpression
[] Attach a test to reproduce your issue, if it is a bug or unexpected behaviour. This is very important. 
I've added test to RefAndLookupTests class, that reproduces the issue:
```
        [TestMethod]
        public void OffsetShouldReturnARange2()
        {
            using (var package = new ExcelPackage())
            {
                var s1 = package.Workbook.Worksheets.Add("Test");
                s1.Cells["B1"].Value = 10d;
                s1.Cells["B2"].Value = 10d;
                s1.Cells["B3"].Value = 10d;
                s1.Cells["A5"].Formula = "COUNTA(OFFSET(Test!B1, 0, 0, Test!B2, Test!B3))";
                s1.Calculate();
                Assert.AreEqual(3d, s1.Cells["A5"].Value);
            }
        }
```
First error occurs when it tries to evaluate 3 and 4 parameters. Excel allows width and height to be substituted from address. Code of OFFSET function requires them only as integers.

Another issue I can observe only in our code, trying to narrow it down. The issue is the first argument of OFFSET function arrives as DataType = Empty, though it's just an excel address reference. And in an expression tree, it looks like normal ExcelAddressExpression, but I think it compiles wrong.

**Comment by zabulus** [comment]
The issue with offset is in SkipArgumentEvaluation property. It set to false, so ParentIsLookupFunction not set for its first parameter, it's not compiled as a range, therefore, OFFSET receives the first parameter as Empty.

**Comment by zabulus** [comment]
Also, OFFSET should return IRangeInfo result. For example, COUNTBLANK(OFFSET(<range 10x10>)) just doesn't work because of the following code:
```
             if(!arg.IsExcelRange)throw new InvalidOperationException("CountBlank only support ranges as arguments");
```

**Comment by swmal** [comment]
Fixed, will be included in next release. The test above is now included in the unit tests.

**Comment by zabulus** [comment]
@swmall
Will this fix include second part with IRangeInfo, or should I fill another issue with unit test?
