### ISSUE TITLE
ZipFile.SaveSelfExtractor.cs missing does not build

### ISSUE THREAD

**Issue by weedkiller** [JanKallman/EPPlus#370]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file` 'C:\EPPlus\EPPlus\Packaging\DotNetZip\ZipFile.SaveSelfExtractor.cs' could not be found.	EPPlus	C:\EPPlus\EPPlus\CSC	1	N/A`

**Comment by heartacker** [comment]
i have the same problem how to deal with this?

**Comment by anewton** [comment]
A quick workaround just to get the source to build is to checkout the previous commit.  You can confirm which one by looking at the history on the EPPlus.csproj file: ([link here](https://github.com/JanKallman/EPPlus/commits/26303b8baf28b680021345f79567f5acf53159f0/EPPlus/EPPlus.csproj)).  There is a missing file in the latest commit.
