### ISSUE TITLE
Typo on Getting Started Wiki page

### ISSUE THREAD

**Issue by mattaze** [JanKallman/EPPlus#371]
Nitpick of a typo.

On Getting Started wiki page, says
https://github.com/JanKallman/EPPlus/wiki/Getting-Started

    ws.Cells[2, 1].Value = "This is cell B1. It is set to bolds";

[2, 1] would be A2
[1, 2] would be B1

Example on other pages do reference as expected.
Maybe an old version where it was [col, row]

**Comment by JanKallman** [comment]
Fixed, sorry about that.
