### ISSUE TITLE
ExcelNamedRangeCollection.Add objects to previously-OK names like R0 and ID1

### ISSUE THREAD

**Issue by marklam** [JanKallman/EPPlus#387]
The following code worked in 4.5.2.1 but not in 4.5.3
```C#
using OfficeOpenXml;

namespace epp
{
    class Program
    {
        static void Main(string[] args)
        {
            var workbook = new ExcelPackage().Workbook;
            var worksheet = workbook.Worksheets.Add("One");

            worksheet.Cells[1, 3].Value = "Hello";
            var cells = worksheet.Cells["A3"];

            worksheet.Names.Add("R0", cells);
            workbook.Names.Add("Q0", cells);
        }
    }
}
```

In 4.5.3, both Names.Add calls generate an exception
```
System.ArgumentException
  HResult=0x80070057
  Message=Name contains invalid characters
  Source=EPPlus
  StackTrace:
   at OfficeOpenXml.ExcelNamedRangeCollection.Add(String Name, ExcelRangeBase Range)
   at epp.Program.Main(String[] args)
```

(I also checked the names are OK to use from within Excel itself)

**Comment by JanKallman** [comment]
Fixed, incorrect validation of defined names

**Comment by marklam** [comment]
Many thanks.

**Comment by GisTep** [comment]
I've just started using 4.5.3.1.  I have the same problem as above.  Has this issue been re-introduced?

Thanks in advance.

**Comment by GisTep** [comment]
Actually I wasn't clear.  The code above to create a workbook works fine.  But if I try to read from an existing file, the Workbook object reports the "Name contains invalid characters" error.  As an example, if I append this code to the code above:

            FileInfo excelFile = new FileInfo(@"sample.xlsx");
            var workbook2 = new ExcelPackage(excelFile);

the Workbook object throws an error. 
[using System.IO is inserted at the top of the code of course]
