### ISSUE TITLE
Can't build solutions

### ISSUE THREAD

**Issue by LeonardoX77** [JanKallman/EPPlus#390]
Hi
I'm very interested to use your project but once I clone, open VS2017 and build I get some errors:

Assets file 'C:\Temp\EPPlus-master\EPPlus\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.

So I try to right click on solution and Restore Nuget packages, then I get this:

All packages are already installed and there is nothing to restore.
Time Elapsed: 00:00:00.0583458
========== Finished ==========
Error occurred while restoring NuGet packages: The operation failed as details for project EPPlus.MultiTarget could not be loaded.

So then in Package Management Concole I try this:
PM> dotnet restore
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.

Then this:
PM> dotnet restore EPPlus.MultiTarget.csproj
MSBUILD : error MSB1009: Project file does not exist.

Or this:
PM> dotnet restore C:\Temp\EPPlus-master\EPPlus\EPPlusTest.Core.csproj
MSBUILD : error MSB1009: Project file does not exist.

Do I have to install or run anything before build the project?

Also in EPPlusTest project there are lots of missing files (I know all of them end with "Test", but you'd update csproj file):
Source file 'C:\Temp\EPPlus-master\EPPlusTest\Address.cs' could not be found.
Source file 'C:\Temp\EPPlus-master\EPPlusTest\Calculation.cs' could not be found.
Source file 'C:\Temp\EPPlus-master\EPPlusTest\SparkLines.cs' could not be found.
Source file 'C:\Temp\EPPlus-master\EPPlusTest\ExcelCellBaseTest.cs' could not be found.
Source file 'C:\Temp\EPPlus-master\EPPlusTest\ExcelStyleTest.cs' could not be found.
Source file 'C:\Temp\EPPlus-master\EPPlusTest\ExcelRangeBaseTest.cs' could not be found.
Source file 'C:\Temp\EPPlus-master\EPPlusTest\VBA.cs' could not be found.
Source file 'C:\Temp\EPPlus-master\EPPlusTest\WorkSheet.cs' could not be found.

Thanks

**Comment by swmal** [comment]
This might be unnecessary to point out, but if you just want to use EPPlus, you dont need to build the source code your self. You can just install the Nuget package from the package manager console.

If you need build the source yourself with Visual Studio 2017 and it doesn't work, you can start by ensuring that you have a version of Visual Studio that supports .NET core 2.0.

**Comment by LeonardoX77** [comment]
Hi, 
I know I can use nugget, I have VS2017 and net core issued, but I like to download and build projects I will use in my own, mainly to learn how things work and cause if I find a bug or something that could be improved and collaborate with a pull request it's better for everyone. But I will follow your suggestion. Thanks anyway

**Comment by swmal** [comment]
Hi,

I tried to clone the repo, opened it and it worked without problems. I have VS 15.9.3.

**Comment by kjkrum** [comment]
EPPlus.Core.sln opens and builds without error. EPPlus.sln is riddled with errors about conflicts between mscorlib and System.Runtime when opened in VS2017 or VS2019. Googling the errors only finds other projects that were configured incorrectly in ways I don't understand.
