### ISSUE TITLE
PROBLEMA AL USAR FLOOR . MATH 

### ISSUE THREAD

**Issue by DAJHER** [JanKallman/EPPlus#392]
Antes que nada buenas tardes. 

Espero puedan ayudarme con un detalle que tengo.

No he podido utilizar la función FLOOR.MATH al abrir el Excel creado la función no se traduce a MULTIPLO.INFERIOR.MAT como debería ser.

Estoy programando en C# framework 4.5 todas las funciones que he utilizado me han funcionado al 100 excepto esa que me ha dado dolores de cabeza no se si estaré haciendo algo mal.

worksheet.Cells["B1:B6"].Formula = "FLOOR.MATH(A1,0.5,0.5)";

**Comment by swmal** [comment]
No hablo espanol, can you translate to english?

**Comment by DAJHER** [comment]
First of all good afternoon.

I hope you can help me with a detail that I have.

I could not use the FLOOR.MATH function when opening the Excel created function does not translate to MULTIPLO.INFERIOR.MAT as it should be.

I am programming in C # framework 4.5 all the functions that I have used have worked at 100 except that that has given me headaches I do not know if I will be doing something wrong.

worksheet.Cells ["B1: B6"]. Formula = "FLOOR.MATH (A1,0.5,0.5)";

**Comment by swmal** [comment]
Hi, 

MATH.FLOOR is unfortunately not implemented in EPPlus yet. You can see all supported functions here: https://github.com/JanKallman/EPPlus/wiki/Supported-Functions

You can implement it yourself and register it, see the ”Implementing Excel functions” in the wiki.
