### ISSUE TITLE
Real row height

### ISSUE THREAD

**Issue by ValentinM92** [JanKallman/EPPlus#4]
Hello,

I create my Excel file dynamicaly using Epplus (C#). When I want to get height of a row(_feuille.Row(i).Height_), I have a wrong result : I got 14.40 (default value), and not the good value (28.80 in my case).

I think that Excel formated visually rows and columns only when the file is opening.

I tried to use _CustomHeight = true_ before get the row height, but it doesn't work.

I published this issue in StackOverFlow (https://stackoverflow.com/questions/46340871/epplus-c-sharp-real-row-height) because is it very urgent, and the new issue link in CodePlex is disabled.

I hope anybody can help me.

Thank you.

**Comment by JanKallman** [comment]
The value in the package (ooxml) and inside of Excel are different. The value is Excel is dependent of your culture. EPPlus returns the ooxml value written to the package.

**Comment by ValentinM92** [comment]
Hello,

Thank you for your answer.
But I did the good way or not ? How I can resolve my issue ?

Thank you.
