### ISSUE TITLE
Installation fails on net core

### ISSUE THREAD

**Issue by Darker** [JanKallman/EPPlus#40]
Currently, the latest version of the package fails to install on .NET Core:
```
Install-Package : Package EPPlus 4.1.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package EPPlus 4.1.1 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
```

**Comment by swmal** [comment]
epplus, will not be compatible with core 1.0. However, 4.5 beta which is compatible with core 2.0 was published today. For 1.0 you can have a look at EPPlus.Core (Nuget) which is an unofficial port of EPPlus.
