### ISSUE TITLE
.net core 3.0 version planning

### ISSUE THREAD

**Issue by michaelongithub** [JanKallman/EPPlus#408]
Hi
planning to update to coming .net core 3.0. If so, timeline?
Or is this not necessary because the current 2.0 version can just be recompiled under 3.0 and will run because no critical dependencies.

Thanks a lot for info
Michael

**Comment by ErikNoren** [comment]
The library targets [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) instead of .NET Core directly. There's no need to recompile or change anything to be compatible with .NET Core 3.0.

**Comment by michaelongithub** [comment]
great, thank You
