### ISSUE TITLE
EPPlus cell.calculate() error when formula contains TRIM function

### ISSUE THREAD

**Issue by MalmeeW** [JanKallman/EPPlus#426]
I want to calculate the formula of a cell and retrieve the calculated value. But it gives `#NAME?` as the cell value when `cell.Calculate()` is executed.  

```  var package = new ExcelPackage();
     var ws = package.Workbook.Worksheets.Add("Test");
     ExcelRange cellTest = ws.Cells[1, 1];
    
     cellTest.Formula = "TRIM( Hello World )";
     cellTest.Calculate();
     var cellCalculatedValue = cellTest.Value;```

Here the `cellTest.Value = #NAME?`

**Comment by swmal** [comment]
The formula engine of EPPlus requires strings to be within

**Comment by MalmeeW** [comment]
https://stackoverflow.com/questions/55061105/epplus-cell-calculate-error-when-formula-contains-trim-function/55073228#55073228

The first reply answers this perfectly.
