### ISSUE TITLE
System.ArgumentOutOfRangeException  INSERTROW

### ISSUE THREAD

**Issue by steph9111** [JanKallman/EPPlus#439]
InsertRow(13, 1, 13) or InsertRow(1, 1) 

System.ArgumentOutOfRangeException 
  HResult=-2146233086
  Message=Row cannot be less than 1.
Nom du paramètre : value
  ParamName=value
  Source=EPPlus
  StackTrace:
       à OfficeOpenXml.ExcelCellAddress.set_Row(Int32 value)
       à OfficeOpenXml.ExcelCellAddress..ctor(Int32 row, Int32 column)
       à OfficeOpenXml.ExcelAddressBase.get_Start()
       à OfficeOpenXml.ExcelNamedRangeCollection.InsertRows(Int32 rowFrom, Int32 rows, ExcelNamedRange namedRange)
       à OfficeOpenXml.ExcelNamedRangeCollection.Insert(Int32 rowFrom, Int32 colFrom, Int32 rows, Int32 cols, Func`2 filter)
       à OfficeOpenXml.ExcelNamedRangeCollection.Insert(Int32 rowFrom, Int32 colFrom, Int32 rows, Int32 cols)
       à OfficeOpenXml.ExcelWorksheet.InsertRow(Int32 rowFrom, Int32 rows, Int32 copyStylesFromRow)

**Comment by parasdaryanani** [comment]
@steph9111 I've got the same issue and I see some others having it too, see here: https://stackoverflow.com/questions/55613182/epplus-insertrow-row-cannot-be-less-than-1-parameter-name-value

Did you find a fix or workaround for this?

**Comment by evgiv0** [comment]
Hello! I have same issue... How can i fix it?

**Comment by parasdaryanani** [comment]
@evgiv0 do you have merged cells near the row where you are calling InsertRow() ?

**Comment by evgiv0** [comment]
@parasdaryanani no, i haven`t. I`m trying to apply it in different places of my template, but it doesn`t work.
I have resolved it by switching to version 4.0.5.
