### ISSUE TITLE
Support for .NETCoreApp 2.0

### ISSUE THREAD

**Issue by timmhagen** [JanKallman/EPPlus#46]
I didn't see where this project was only for v4.6.1 of the Standard .NET Framework so I get the following warning in Error List.

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'EPPlus 4.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.	myproject.csproj	1	

The library seems to work, at least for what I am doing in ASPNET Core 2, other than this warning in the error section.  Can you update it so that the target works with Core 2?

**Comment by danielwertheim** [comment]
Would rather have this "offical" EPPlus to support .NET Standard (and thereby Core), should be doable since a fork has done exactly that: https://github.com/VahidN/EPPlus.Core

@JanKallman Will that happen or is your recommendation to use the non offical .NET Core enabled project?

**Comment by timmhagen** [comment]
Thanks @danielwertheim  I will wait to hear from @JanKallman to see the response.  Its good to know of an unofficial version available for Core.  Hopefully @JanKallman  will make/merge into an official core version, so that I can get rid of this warning/error other than ignoring it.

**Comment by austingriff** [comment]
I second this issue! Would love to see this version supported with .NETCore App 2.0.  I currently have VahidN's EPPlus.Core working in my solution, but his code is not as up-to-date as this version. (i.e. EPPlus.Core has issues transforming formulas using R1C1 notation)

**Comment by austingriff** [comment]
I second this issue @timmhagen ! 

@JanKallman is this in the scope of work for the future? I would love to see this version supported with .NETCore App 2.0. I currently have VahidN's EPPlus.Core working in my solution, but his code is not as up-to-date as this version. (i.e. EPPlus.Core has issues transforming formulas using R1C1 notation)

**Comment by swmal** [comment]
Have just published 4.5 beta on Nuget, which supports core 2.0.

**Comment by djanosik** [comment]
Will it be possible to replace `CoreCompat.System.Drawing.v2` with the official `System.Drawing.Common`?

**Comment by djanosik** [comment]
It seems [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common) is based on Mono's implementation and is cross-platform. Will you replace the `CoreCompat.System.Drawing.v2` package?
