### ISSUE TITLE
How to move data validations when we delete an excel column in EPPlus?

### ISSUE THREAD

**Issue by bannu28** [JanKallman/EPPlus#482]
Ex: I have an excel master template with some data validations at few columns. when i delete a column (worksheet.Delete[5]) prior to the validation column my column is deleted but validation remain at the original column.

**Comment by lpch534** [comment]
try saveas a new excel file

**Comment by bannu28** [comment]
Hi, 
I found the solution by creating Named lists instead of creating list at column.
