### ISSUE TITLE
Doesn't work on OSX

### ISSUE THREAD

**Issue by rmarinho** [JanKallman/EPPlus#50]
Should work cross platform

**Comment by JanKallman** [comment]
I have swiched to the new Official Microsoft - System.Drawing.Common in 4.5.0.1-Beta 2, Some please give it another try

**Comment by danielodievich** [comment]
I changed to 4.5.0.1-beta 2 and the "Unable to load DLL 'gdiplus': The specified module or one of its dependencies could not be found." no longer occurs when running on Sierra with .net standard 2.0.2. Thanks.

I did not try the AutoFit of the columns - changed the width to be hardcoded to specific value instead.

**Comment by JanKallman** [comment]
The works in 4.5.1, if you install libgdiplus as described in the readme.txt

**Comment by paladin2005** [comment]
Still the error... Jul/2019
My solution for the server is:
`if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) ws.Cells.AutoFitColumns();`
