### ISSUE TITLE
Table formula rewritten with #ref instead of columns

### ISSUE THREAD

**Issue by chrismasters** [JanKallman/EPPlus#521]
When referencing a column in [@ColumnName] style in a formula that is part of a table, the resulting formula is rewritten with the column name as #REF

**Comment by El-Gor-do** [comment]
Even though Excel shows the cell formula as "[@ColumnName]", in Open Xml the CalculatedColumnFormula format is "TableName[[#This Row],[ColumnName]]" where "TableName" is the name of the table and "ColumnName" is the referenced table column's header value.

**Comment by chrismasters** [comment]
Perfect.. thanks!
