### ISSUE TITLE
Add support for netstandard2.0

### ISSUE THREAD

**Issue by VahidN** [JanKallman/EPPlus#53]
Currently `EPPlus 4.5.0-beta` supports `.NETCoreApp 2.0`. In this case, It can't be used from a class library project.
## Steps to reproduce
```
dotnet new classlib
dotnet add package EPPlus --version 4.5.0-beta
```

## Output
```
warn : Package 'EPPlus 4.5.0-beta' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

It can be fixed by changing `netcoreapp2.0` [in csproj](https://github.com/JanKallman/EPPlus/blob/master/EPPlus/EPPlus.MultiTarget.csproj) file to `netstandard2.0`.

![cfdfb364429e443887015c63feea0c84](https://user-images.githubusercontent.com/766010/32714270-4fb1f77a-c862-11e7-9c72-90dc66fc5827.png)

**Comment by JanKallman** [comment]
Thanks, I have changed target framework to netstandard2.0 in Beta 2, so give it another try.
Also see https://github.com/JanKallman/EPPlus/issues/59

And thanks for your work on the EPPlus.Core fork :).
