### ISSUE TITLE
can i use EPPlus to read and wtire file .xls

### ISSUE THREAD

**Issue by ducdm87** [JanKallman/EPPlus#532]
I need use EPPlus  to read file .xls (for excel 97-2003). Does EPPlus  support work it?

Thanks and best regards

**Comment by ZUOXIANGE** [comment]
EPPlus is a .NET library that reads and writes Excel files using the Office Open XML format (xlsx). You can try [NPOI](https://github.com/tonyqus/npoi).

**Comment by ducdm87** [comment]
I was try NPOI and it work very good.

Thanks and best regards.
