### ISSUE TITLE
Headers and Footers scale with document

### ISSUE THREAD

**Issue by KusovAA** [JanKallman/EPPlus#54]
Pls add code in file ExcelHeaderFooter.cs for support flag Headers and Footers scale with document
![image](https://user-images.githubusercontent.com/33625595/32724821-97f97300-c894-11e7-87a7-de4002e2f5b4.png)
       
 `const string scaleWithDocPath = "@scaleWithDoc";`
        
`public bool scaleWithDoc`
        `{`
`            get`
           ` {`
               ` return GetXmlNodeBool(scaleWithDocPath);`
            `}`
            `set`
            `{`
                `SetXmlNodeString(scaleWithDocPath, value ? "1" : "0");`
            `}`
       ` }`

**Comment by JanKallman** [comment]
Added to 4.5.1
