### ISSUE TITLE
Rows and Columns of ExcelRange always "1"

### ISSUE THREAD

**Issue by zhuxb711** [JanKallman/EPPlus#555]
I want to get RowIndex and ColumnIndex of a Cell

but its "Rows" and "Columns" property always "1"

like this:

<img width="528" alt="无标题" src="https://user-images.githubusercontent.com/42038175/65825143-fafee200-e2a5-11e9-890b-b53caec52b02.png">

**Comment by rubend30** [comment]
`ExcelRange.Columns` represents how many columns the range occupies. Use the `ExcelRange.Start.Row` and `ExcelRange.Start.Column` to get the actual indexes.
If the range uses multiple rows and/or columns than the `ExcelRange.End` can be used together with `ExcelRange.Start`.

**Comment by zhuxb711** [comment]
Got it, Thanks
