### ISSUE TITLE
LoadFromArrays error with empty collection

### ISSUE THREAD

**Issue by kfreimanis** [JanKallman/EPPlus#56]
Strange error by following code
`ExcelPackage pck = new ExcelPackage();`
`ExcelWorksheet ws = pck.Workbook.Worksheets.Add("test");`
`ws.Cells["A1"].LoadFromArrays(Enumerable.Empty<object[]>());`

Is this meant to throw exception if so it is unclear to user what is he doing wrong.
I am happy to create pull request with fix only i need to know throw an error or do nothing?

Looking at 'LoadFromDataTable' LoadFromArrays with empty collection should return null

**Comment by JanKallman** [comment]
Fixed in. 4.5.1
