### ISSUE TITLE
COUNTIFS calculating incorrectly

### ISSUE THREAD

**Issue by lolsoftware** [JanKallman/EPPlus#577]
When there are multiple range-criteria pairs provided to the COUNTIFS function, then EPPlus calculates the outcome incorrectly.
Please see the attached Excel file and the attached source code.

[toCalc.xlsx](https://github.com/JanKallman/EPPlus/files/3824985/toCalc.xlsx)
[Program.zip](https://github.com/JanKallman/EPPlus/files/3824981/Program.zip)

**Comment by lolsoftware** [comment]
I think that this issue can be addressed by applying the following fix to the CountIfs class (in OfficeOpenXml.FormulaParsing.Excel.Functions.Math).
`
/*---Original code :---*/

public override CompileResult Execute(IEnumerable<FunctionArgument> arguments, ParsingContext context)
{
	var functionArguments = arguments as FunctionArgument[] ?? arguments.ToArray();
	ValidateArguments(functionArguments, 2);
	var argRanges = new List<ExcelDataProvider.IRangeInfo>();
	var criterias = new List<string>();
	for (var ix = 0; ix < 30; ix += 2)
	{
		if (functionArguments.Length <= ix) break;
		var rangeInfo = functionArguments[ix].ValueAsRangeInfo;
		argRanges.Add(rangeInfo);
		var value = functionArguments[ix + 1].Value != null ? functionArguments[ix + 1].Value.ToString() : null;
		criterias.Add(value);
	}
	IEnumerable<int> matchIndexes = GetMatchIndexes(argRanges[0], criterias[0]);
	var enumerable = matchIndexes as IList<int> ?? matchIndexes.ToList();
	for (var ix = 1; ix < argRanges.Count && enumerable.Any(); ix++)
	{
		var indexes = GetMatchIndexes(argRanges[ix], criterias[ix]);
		matchIndexes = enumerable.Intersect(indexes);
	}

	return CreateResult((double)matchIndexes.Count(), DataType.Integer);
}

/*------*/
/*---Fixed code :---*/

public override CompileResult Execute(IEnumerable<FunctionArgument> arguments, ParsingContext context)
{
	var functionArguments = arguments as FunctionArgument[] ?? arguments.ToArray();
	ValidateArguments(functionArguments, 2);
	var argRanges = new List<ExcelDataProvider.IRangeInfo>();
	var criterias = new List<string>();
	for (var ix = 0; ix < 30; ix += 2)
	{
		if (functionArguments.Length <= ix) break;
		var rangeInfo = functionArguments[ix].ValueAsRangeInfo;
		argRanges.Add(rangeInfo);
		var value = functionArguments[ix + 1].Value != null ? functionArguments[ix + 1].Value.ToString() : null;
		criterias.Add(value);
	}
	IEnumerable<int> matchIndexes = GetMatchIndexes(argRanges[0], criterias[0]);
	for (var ix = 1; ix < argRanges.Count && matchIndexes.Any(); ix++)
	{
		var indexes = GetMatchIndexes(argRanges[ix], criterias[ix]);
		matchIndexes = matchIndexes.Intersect(indexes);
	}

	return CreateResult((double)matchIndexes.Count(), DataType.Integer);
}

/*------*/
`

**Comment by swmal** [comment]
Hi @lolsoftware and many thanks for a well documented bug report. I have fixed this in EPPlus 5 and have also added a unit test for it. Your example also highlighted the fact that the GetMatchIndexes function went through the maximum number of rows (over a million) since the ranges had no row specified.
