### ISSUE TITLE
Adding ProtectedRanges always use the name of the last added range  

### ISSUE THREAD

**Issue by EsbenRud** [JanKallman/EPPlus#58]
Thanks for an excellent product.
However when I add more than one ProtectedRange to a worksheet, only the last added range is in the resulting file. I have attached a sample-solution that can re-produce the bad behavior. After adding range2 it looks like the name of the range1 object is modified to the name of range2.
[ConsoleApp4.zip](https://github.com/JanKallman/EPPlus/files/1473784/ConsoleApp4.zip)

**Comment by EsbenRud** [comment]
I have tried with your new commit. Now both ProtectedRanges were added (ConsoleApp4.zip), but when I try to open Test.xlsx in Excel, I get an error saying the file is corrupted. See screenshot.
![image](https://user-images.githubusercontent.com/12291383/33255307-3db1a142-d34d-11e7-8f80-67afa309c5d1.png)

**Comment by JanKallman** [comment]
That's odd. I just tried it and I get no error. Can you attach the failing xlsx file?

**Comment by EsbenRud** [comment]
Yes, here it is.
[Test.xlsx](https://github.com/JanKallman/EPPlus/files/1505049/Test.xlsx)

**Comment by EsbenRud** [comment]
Did you get an error when opening Test.xlsx?

**Comment by JanKallman** [comment]
Yes, but I can't reproduce the behavior. Do you get the same result using beta 4.5.0.1 beta nuget package?
For some reason you get two sheetData element in the sheet1.xml file...

```xml
<sheetData>
<row r="1">
<c r="A1" t="s" s="0">
<v>0</v>
</c>
<c r="B1" t="s" s="0">
<v>1</v>
</c>
<c r="C1" t="s" s="0">
<v>2</v>
</c>
</row>
<row r="2">
<c r="A2" t="s" s="0">
<v>3</v>
</c>
<c r="B2" t="s" s="0">
<v>4</v>
</c>
<c r="C2" t="s" s="0">
<v>5</v>
</c>
</row>
</sheetData>
<sheetData/>
```

**Comment by EsbenRud** [comment]
I tried with 4.5.0.1 beta and now it works perfectly. Do you know when 4.5.0.1 will be available?
