### ISSUE TITLE
Investigate changing .NET core target to netstandard2.0 , not netcoreapp2.0

### ISSUE THREAD

**Issue by boekabart** [JanKallman/EPPlus#59]
I noticed that the current .NET core beta targets netcoreapp2.0, instead of the preferred netstandard2.0 (See https://stackoverflow.com/questions/45867239/advantages-of-netcoreapp2-0-vs-netstandard2-0-for-a-library-project )

Is it not possible to target the more generic library instead? Or even .netstandard < 2?

**Comment by JanKallman** [comment]
I Added a new target for netstandard2.0 in the [EPPlus.MultiTarget.csproj](https://github.com/JanKallman/EPPlus/blob/master/EPPlus/EPPlus.MultiTarget.csproj) (in the next commit). And for all I can see it generates a .Net Standard 2.0 version in the Nuget Package. EPPlus 4.5 is only compatible with .Net Core 2.0, so I  assume earlier versions of .Net Standard will not work? I'm no expert in this area so I hope you or some else can answer this question: Is it safe to remove the netcoreapp2.0 target when i add the netstandard2.0 target or should I leave the both in the Nuget package?

**Comment by boekabart** [comment]
I'm no expert, but what I read,  netcoreapp2.0 is a superset of netstandard2.0 , so if it compiles with netstandard, that's all you need, and it can be used more generically (for example, and important in my case, as a reference in another .netstandard2.0 library).

Btw, I'm sure you're aware of this https://github.com/VahidN/EPPlus.Core 'fork' - which seems to be able to target 'lesser' netstandard versions too, somehow.
Maybe it's an idea to take a look at how he pulled that off, and target lower netstandard versions as well?

**Comment by JanKallman** [comment]
Yes, I'm aware of this fork. I converted the Project to Core 1.1 first, but desided to go with core 2.0 as a lot of stuff was missing in 1.1. (like Datasets, Encodings and other stuff). Also the Microsoft version of System.Drawing will be for 2.0, as I understand it. Currently we relaying on an unofficial preview for this, so I hope ms will release this soon. Scott Hunter said after the summer at MS Build, but I guess it's been 
delayed.

**Comment by JanKallman** [comment]
I have changed target framework to netstandard2.0 in Beta 2, so give it another try.
