### ISSUE TITLE
Wiki Page Formula Calculation: .Calculate method availability

### ISSUE THREAD

**Issue by jochenwezel** [JanKallman/EPPlus#599]
The .Calculate methods for Workbook etc. are available only after a
```C#
using OfficeOpenXml;
```

Following changes to Wiki page https://github.com/JanKallman/EPPlus/wiki/Formula-Calculation are suggested to area `Some common mistakes` for another bullet point:

```
* The .Calculate() methods are available on Workbook, Worksheet and Range level only after a `using OfficeOpenXml;`. Alternatively, you might call method OfficeOpenXml.CalculationExtension.Calculate()
```

**Comment by swmal** [comment]
Thanks! Have updated the wiki.
