### ISSUE TITLE
Error while reading password protected Excel file

### ISSUE THREAD

**Issue by arek98** [JanKallman/EPPlus#60]
When trying to load password protected file exception is thrown with message "Unable to read beyond the end of the stream."
This is because in ExcelPackage.cs file, line 1138 when DecryptPackage is called encrStream is at the end (CopyStream caused position to move to the end).
Because of that Read in CompundDocumentFile fails.
Moving encrStream to beginning before calling DecryptPackage fixes problem and file is decrypted correctly.

                    Stream encrStream = new MemoryStream();
                    CopyStream(input, ref encrStream);
                    EncryptedPackageHandler eph = new EncryptedPackageHandler();
                    Encryption.Password = Password;
                    if (encrStream.CanSeek)
                        encrStream.Seek(0, SeekOrigin.Begin);
                    ms = eph.DecryptPackage((MemoryStream)encrStream, Encryption);

**Comment by JanKallman** [comment]
Thanks, will add a fix in the next commit

**Comment by JanKallman** [comment]
Fixed in 4.5.1
