### ISSUE TITLE
LoadFromDataTable with PrintHeaders=True does not load headers if datatable does not contain rows

### ISSUE THREAD

**Issue by ch-eng** [JanKallman/EPPlus#61]
Our previous version is 2.9.  Trying version 4.1 because of unresolved errors trying to open XLSX files.  Anyway, when saving data to sheets now (EPPlus v4.1), via 

currentSheet.Cells("A1").LoadFromDataTable(Data, True)

when the "Data" datatable contains no rows (but still contains named columns), the headers are no longer saved to the sheet.

Lines ~1867-1870 in ExcelRangeBase.cs confirm this change was made.  Can we still have an option to write column headers to a sheet even if there are no rows in the datatable?

**Comment by robws** [comment]
Is there a way to pull this fix via NuGet to replace 4.1.1?

**Comment by JanKallman** [comment]
Fixed in 4.5.1
