### ISSUE TITLE
Formula Calculation in 4.5.3.3 has bug after calculate call the cell value property return #Value

### ISSUE THREAD

**Issue by minren118** [JanKallman/EPPlus#620]
in 4.5.3.2 has no problem ,but in  4.5.3.3 
![image](https://user-images.githubusercontent.com/28550438/74578300-cb3f4500-4fce-11ea-8de6-20bab732917b.png)

**Comment by swmal** [comment]
just so we get the full picture... what are the values/formulas in D3 and C3? And what .NET framework/core version are you running?

**Comment by minren118** [comment]
sorry for the lack of info,I run in .net framework 4.0，D3 and C3 is constant number,I use 4.5.3.2 is OK,but Change then 4.5.3.3 will return #Value .
&nbsp;




李伟坚-Excel催化剂作者
Office365社区天鸣科技


 联系我









&nbsp;

**Comment by swmal** [comment]
Thanks. Can you log the calculation as described under "Trouble shooting/logging" in this page https://github.com/JanKallman/EPPlus/wiki/Formula-Calculation and publish the log here?

**Comment by swmal** [comment]
Assuming we can close this issue.
