### ISSUE TITLE
Array formulas cannot be recognized after parsing

### ISSUE THREAD

**Issue by roelvandersteen** [JanKallman/EPPlus#63]
Reading array formulas is not yet supported (according to the comment in `LoadCells(Xmlreader)` at line 1358 `else if (t == "array")`), but there is some basic support.

Unfortunately, however, at this point there is no way to recognize that a formula was originally an array formula. I propose to solve this by setting the `CellFlags.ArrayFormula` flag for the relevant cell.

PR follows.

**Comment by JanKallman** [comment]
Fixed in 4.5.1
