### ISSUE TITLE
Error: Requested value 'baseline' was not found.

### ISSUE THREAD

**Issue by paaresh** [JanKallman/EPPlus#69]
I got Error "Requested value 'baseline' was not found." while saving XLSX file after editing file.
The error is because "baseline" is not available in enum ExcelVerticalAlignmentFont. I have attached screenshot for error line.
I observe this error occurs only while editing xlsx file created by some other library.

>     public enum ExcelVerticalAlignmentFont
>     {
>         None,
>         Subscript,
>         Superscript
>     }
> 

![xlsx_1](https://user-images.githubusercontent.com/33928694/33196966-563294d4-d108-11e7-96cb-d61d927e1c06.png)

**Comment by KarenArzumanyan** [comment]
I confirm this problem.
I had the same exeption when opening a file created by ClosedXML.

**Comment by Hex-99** [comment]
I can confirm that this is an issue in reading .xlsx files created by systems that have a vertAlign of baseline in the style.
If the node: **<x:vertAlign val="baseline" />** is present in styles.xml, accessing the worksheet object crashes with above error.

**Comment by KarenArzumanyan** [comment]
Unfortunately, I can not now.  :(

**Comment by paaresh** [comment]
@KarenArzumanyan , I need check again with new version.

**Comment by JanKallman** [comment]
Fixed in 4.5.1
