### ISSUE TITLE
Scale and Links Dirty Properties - Email server rejecting Excel

### ISSUE THREAD

**Issue by prateek-codex** [JanKallman/EPPlus#75]
While generating excel with EPPlus, the "Links dirty" and "Scale" properties of generated file are empty (please refer to attached image) ![excelissue](https://user-images.githubusercontent.com/2369925/33604131-e8a8b610-d9da-11e7-9534-25eb9bc36b40.PNG)

Which, I believe is the reason that Email server is rejecting generated Excel files.

When I open the file, save it and send it again, Email is sent successfully.
By default, when we create/update any excel files, these two properties are set to "No".

I am unable to find any method to set these two properties (tried excelPackage.Workbook.Properties).

Please revert if there is something that could be done to set these two properties.

**Comment by JanKallman** [comment]
Added requested properties in 4.5.1
