### ISSUE TITLE
package.Save() takes too much time for large data

### ISSUE THREAD

**Issue by gajanandeshpande27** [JanKallman/EPPlus#90]
Excel sheet having 150000 rows and 70 columns data takes nearly 10 to 12 min to save the file.
on EPPlus version 4.0.5.

Can we reduce the time to save file? The file size is approximately 35MB.

**Comment by igor-eremyashev** [comment]
In my expirence there is a quadratic dependency between number of rows and save time:
100 rows takes 10 seconds to save.
200 rows takes 38 seconds to save.
